shellEmulator: true

packages:
  - packages/*

overrides:
  beasties: 'workspace:*'
  vite-plugin-beasties: 'link:.'
ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks
