shellEmulator: true

packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - simple-git-hooks

overrides:
  beasties: "workspace:*"
  vite-plugin-beasties: "link:."
